### ISSUE TITLE
Anyway to make it work on heroku? 

### ISSUE THREAD

**Issue by Akane7101** [seriaati/enka-card-api#63]

**Comment by seriaati** [comment]
Maybe check this article? https://jnikenoueba.medium.com/how-to-deploy-a-fastapi-api-on-heroku-7d805cb83ffa

**Comment by Akane7101** [comment]
> Maybe check this article? https://jnikenoueba.medium.com/how-to-deploy-a-fastapi-api-on-heroku-7d805cb83ffa

Yeah i tried that earlier.. Added the procfile.. Added requirements.txt..yes it deploys but it never works.. Not sure what I'm missing XD

**Comment by seriaati** [comment]
Can you provide more details to what is not working? You're welcome to slip into my Discord DM if you want to.
